import type { Level, MiniGame, Badge } from '@/types/game';

export const INITIAL_LEVELS: Level[] = [
  {
    id: 1,
    name: 'Addition Beginner',
    operation: 'addition',
    difficulty: 'beginner',
    unlocked: true,
    stars: 0,
    completed: false,
    requiredStars: 0,
  },
  {
    id: 2,
    name: 'Addition Advanced',
    operation: 'addition',
    difficulty: 'advanced',
    unlocked: false,
    stars: 0,
    completed: false,
    requiredStars: 3,
  },
  {
    id: 3,
    name: 'Subtraction Beginner',
    operation: 'subtraction',
    difficulty: 'beginner',
    unlocked: false,
    stars: 0,
    completed: false,
    requiredStars: 6,
  },
  {
    id: 4,
    name: 'Subtraction Advanced',
    operation: 'subtraction',
    difficulty: 'advanced',
    unlocked: false,
    stars: 0,
    completed: false,
    requiredStars: 9,
  },
  {
    id: 5,
    name: 'Multiplication Beginner',
    operation: 'multiplication',
    difficulty: 'beginner',
    unlocked: false,
    stars: 0,
    completed: false,
    requiredStars: 12,
  },
  {
    id: 6,
    name: 'Multiplication Advanced',
    operation: 'multiplication',
    difficulty: 'advanced',
    unlocked: false,
    stars: 0,
    completed: false,
    requiredStars: 15,
  },
  {
    id: 7,
    name: 'Mixed Operations Beginner',
    operation: 'mixed',
    difficulty: 'beginner',
    unlocked: false,
    stars: 0,
    completed: false,
    requiredStars: 18,
  },
  {
    id: 8,
    name: 'Mixed Operations Advanced',
    operation: 'mixed',
    difficulty: 'advanced',
    unlocked: false,
    stars: 0,
    completed: false,
    requiredStars: 21,
  },
];

export const MINI_GAMES: MiniGame[] = [
  {
    id: 1,
    name: 'Classic Quest',
    description: 'Solve math problems in classic mode',
    theme: 'classic',
    requiredStars: 0,
    unlocked: true,
    icon: '📚',
  },
  {
    id: 2,
    name: 'Math Racer',
    description: 'Race your car by solving problems',
    theme: 'racing',
    requiredStars: 5,
    unlocked: false,
    icon: '🏎️',
  },
  {
    id: 3,
    name: 'Space Mission',
    description: 'Launch your rocket to planets',
    theme: 'space',
    requiredStars: 15,
    unlocked: false,
    icon: '🚀',
  },
  {
    id: 4,
    name: 'Balloon Pop',
    description: 'Pop balloons with correct answers',
    theme: 'balloons',
    requiredStars: 25,
    unlocked: false,
    icon: '🎈',
  },
  {
    id: 5,
    name: 'Dino Run',
    description: 'Help the dinosaur run and jump',
    theme: 'dinosaur',
    requiredStars: 40,
    unlocked: false,
    icon: '🦕',
  },
  {
    id: 6,
    name: 'Bike Race',
    description: 'Race on your motorcycle',
    theme: 'bike',
    requiredStars: 55,
    unlocked: false,
    icon: '🏍️',
  },
  {
    id: 7,
    name: 'Table Tennis',
    description: 'Play table tennis with math',
    theme: 'tennis',
    requiredStars: 70,
    unlocked: false,
    icon: '🏓',
  },
];

export const BADGES: Badge[] = [
  {
    id: 1,
    name: 'First Victory',
    description: 'Complete your first level',
    icon: '🏆',
    unlocked: false,
    condition: { type: 'first_win', value: 1 },
  },
  {
    id: 2,
    name: 'Star Collector',
    description: 'Earn 10 stars',
    icon: '⭐',
    unlocked: false,
    condition: { type: 'stars', value: 10 },
  },
  {
    id: 3,
    name: 'Math Genius',
    description: 'Earn 25 stars',
    icon: '🌟',
    unlocked: false,
    condition: { type: 'stars', value: 25 },
  },
  {
    id: 4,
    name: 'Problem Solver',
    description: 'Solve 50 problems',
    icon: '🧮',
    unlocked: false,
    condition: { type: 'problems_solved', value: 50 },
  },
  {
    id: 5,
    name: 'Math Master',
    description: 'Solve 100 problems',
    icon: '🎓',
    unlocked: false,
    condition: { type: 'problems_solved', value: 100 },
  },
  {
    id: 6,
    name: 'Streak Starter',
    description: 'Get a 5 answer streak',
    icon: '🔥',
    unlocked: false,
    condition: { type: 'streak', value: 5 },
  },
  {
    id: 7,
    name: 'Streak Champion',
    description: 'Get a 10 answer streak',
    icon: '💫',
    unlocked: false,
    condition: { type: 'streak', value: 10 },
  },
  {
    id: 8,
    name: 'Unstoppable',
    description: 'Get a 20 answer streak',
    icon: '⚡',
    unlocked: false,
    condition: { type: 'streak', value: 20 },
  },
];

export const QUESTIONS_PER_LEVEL = 10;
export const TIME_BONUS_THRESHOLD = 5;
export const PERFECT_SCORE_STARS = 3;
export const GOOD_SCORE_STARS = 2;
export const PASS_SCORE_STARS = 1;
